apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: {{ .Values.db.image }}
          name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.postgresPassword }}
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}