apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "voting-app.fullname" . }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.vote.enabled }}
          - path: /vote
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.vote.serviceName }}
                port:
                  number: {{ .Values.vote.servicePort }}
          {{- end }}
          {{- if .Values.result.enabled }}
          - path: /result
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.result.serviceName }}
                port:
                  number: {{ .Values.result.servicePort }}
          {{- end }}
          {{- if .Values.worker.enabled }}
          - path: /worker
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.worker.serviceName }}
                port:
                  number: {{ .Values.worker.servicePort }}
          {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}