apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: NodePort
  ports:
    - name: "result-service"
      port: 8081
      targetPort: 80
      nodePort: {{ .Values.result.nodePort }}
  selector:
    app: result