apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kibana
spec:
  type: {{ .Values.serviceType | default "ClusterIP"}}
  ports:
  - port: 5601
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.nodePort | default "32100"}}
    {{- end }}
  selector:
    app: kibana
