{{ if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
  labels:
    app: iperf-server
  namespace: iperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      imagePullSecrets:
      - name: nexus-iperf
      volumes:
      - name: shared-volume
        emptyDir: {}
      containers:
      - name: sidecar
        image: nicolaka/netshoot
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sleep", "3650d" ]
        securityContext:
          capabilities:
            add: [ "NET_ADMIN" ]
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
        - name: shared-volume
          mountPath: /log
          
      - name: iperf
        image: mlabbe/iperf
        imagePullPolicy: Always
        args:
          - '-s'
          - '-p'
          - '5201'
        ports:
        - containerPort: 5201
          name: server
{{- end }}