apiVersion: v1
kind: Service
metadata:
  name: "kubevirt-svc"
spec:
  type: NodePort
  ports:
  - name: ubuntu-vm-ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/name: ubuntu-with-iperf-replicaset