apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: { { .Release.Namespace } }
spec:
  type: { { .Values.service.type | default "NodePort" } }
  ports:
    - name: ubuntu-vm-ssh
      port: { { .Values.service.port | default "22" } }
      protocol: TCP
      targetPort: { { .Values.service.targetPort | default "22" } }
  selector:
    kubevirt.io/name: { { .Release.Name } }
