name: Helm Package Workflow

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Helm
        uses: azure/setup-helm@v1

      - name: Package Voting App Chart
        run: |
          helm package voting-app -d packages/
      
      - name: Commit and Push Packages
        run: |
          git checkout -b packages
          git config --global user.email "actions@gmail.com"
          git config --global user.name "GitHub Actions"
          git add packages/*
          git commit -m "Added Voting Helm package"
          helm repo index . --url https://vivekbangare.github.io/helmcharts/

      - name: Push changes to repository
        run: git push https://vivekbangare:${{ secrets.GH_TOKEN }}@github.com/vivekbangare/helmcharts.git packages
        
