name: Helm Package Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up Helm
        uses: azure/setup-helm@v1

      - name: Package Voting App Chart
        run: |
          mkdir -p packages
          helm package voting-app -d packages/

      - name: Switch to packages branch
        run: |
          git fetch origin packages || true
          git checkout packages || git checkout -b packages
          git pull origin packages || true
          cp packages/*.tgz ./
          helm repo index . --url https://vivekbangare.github.io/helmcharts/packages/
          mkdir -p packages
          mv *.tgz packages/
          mv index.yaml packages/

      - name: Commit and Push Packages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "actions@gmail.com"
          git config --global user.name "GitHub Actions"
          git add packages/
          git commit -m "Added/Updated Voting Helm package" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/vivekbangare/helmcharts.git packages
